name: CdrVephilimEconomy
version: '0.1.0-beta.1-RC1'
main: id.cdr.vephilimeconomy.CdrVephilimEconomy
api-version: '1.21.11'
authors: [MenkiPlugcore]
description: NPC-first economy for Vephilim Roleplay.
website: https://github.com/MenkiPlugcore/CdrVephilimEconomy
depend: [Citizens, Vault]

permissions:
  cdrvephilimeconomy.admin:
    description: Administrative permission for CdrVephilimEconomy.
    default: op
